-- ACI Sovereign Build
import Lake
open Lake DSL

package "my_project" where
  srcDir := "."

require mathlib from git "https://github.com/leanprover-community/mathlib4" @ "v4.31.0"

lean_lib AntaresCategory
lean_lib PhysicsCore
lean_lib SpineLanguage
lean_lib SovereignHamiltonian
lean_lib MC2Engine
lean_lib AM10
lean_lib MoruzinLaw
lean_lib N7Spine
lean_lib Synaptic_Weights
lean_lib Governor
lean_lib MyProject
lean_lib ACIManifold
lean_lib Manifold21
lean_lib AWMCore
lean_lib Matrix7
lean_lib Optimus7
lean_lib Optimus7Quantum
lean_lib QuantumCore
lean_lib EnergyDomain
lean_lib VerifyState
lean_lib InformationGeometry
lean_lib NumberTheoryCore
lean_lib OptimalControl
lean_lib StochasticDifferentialEquations
lean_lib TopologicalDataAnalysis
lean_lib StatisticalMechanics
lean_lib ErgodicTheory
lean_lib ConvexAnalysis
lean_lib ControlTheory
lean_lib OptimalTransport
lean_lib RenormalizationGroup
lean_lib ConformalFieldTheory
lean_lib QuantumInformation
lean_lib WaveletAnalysis
lean_lib CompressedSensing
lean_lib GameTheory
lean_lib QuantumErrorCorrection
lean_lib FunctionalAnalysis
lean_lib MeasureTheory
lean_lib AbstractAlgebra
lean_lib NumberTheory
lean_lib StringTheory
lean_lib QuantumGravity
lean_lib HomologicalAlgebra
lean_lib RepresentationTheory
lean_lib DynamicalSystems
lean_lib Combinatorics
lean_lib ComplexAnalysis
lean_lib AlgebraicGeometry
lean_lib SetTheory
lean_lib TopologyAdvanced
lean_lib LinearAlgebra
lean_lib ProbabilityTheory
lean_lib HarmonicAnalysis
lean_lib NumericalAnalysis
lean_lib PartialDifferentialEquations
lean_lib GraphTheory
lean_lib InformationTheoryAdvanced
lean_lib OperatorTheory
lean_lib CodingTheory
lean_lib CryptographyTheory
lean_lib FluidDynamics
lean_lib Thermodynamics
lean_lib GeneralRelativity
lean_lib QuantumFieldTheory
lean_lib NuclearPhysics
lean_lib BioinformaticsTheory
lean_lib CondensedMatterPhysics
lean_lib PlasmaPhysics
lean_lib Optics
lean_lib AcousticsWaves
lean_lib AtomicMolecularPhysics
lean_lib FunctionalEquations
lean_lib SignalProcessing
lean_lib ComputationalComplexity
lean_lib FormalLanguageTheory
lean_lib OptimizationTheory
lean_lib VariationalCalculus
lean_lib IntegralEquations
lean_lib MathematicalBiology
lean_lib MathematicalChemistry
lean_lib MathematicalEconomics
lean_lib SymplecticTopology
lean_lib ContactGeometry
lean_lib NoncommutativeGeometry
lean_lib OrderTheory
lean_lib UniversalAlgebra
lean_lib TropicalGeometry
lean_lib MotivicCohomology
lean_lib ArithmeticGeometry
lean_lib AnalyticNumberTheory
lean_lib AdditiveNumberTheory
lean_lib DiscreteMathematics
lean_lib AWM_NS_Master
lean_lib ACIMegaCore_1790387842
lean_lib ACIFormalCore_v2
lean_lib ACISynthesisCore_1790384450_v2
lean_lib ACISignedCore_1790385282_v2
lean_lib ACISignedCore_1790385887_v2
lean_lib ACICorpusCore_1790386130_v2
lean_lib ACICorpusCore_1790386473_v2
lean_lib ACIRecursiveCore_1790387036_v2
lean_lib ACIMegaCore_1790392608
lean_lib ACIMegaCore_1790393333
lean_lib ACIMegaCore_1790393390
lean_lib ACIMegaCore_1790395136
lean_lib ACIMegaCore_1790408288
lean_lib AlgebraicTopology

@[default_target]
lean_lib AWM21

lean_exe aci_bootstrap where
  root := `Main
