PRIMARY_KEY_ENABLED=YES
EMERGENCY_KEY_ENABLED=YES
RECOVERY_KEY_ENABLED=YES

PRIMARY_KEY_AUDIT=ENABLED
EMERGENCY_KEY_AUDIT=ENABLED
RECOVERY_KEY_AUDIT=ENABLED

FAILED_ATTEMPT_LIMIT=3
LOCK_ON_FAILURE=YES
